language: csharp
solution: Discord.Addons.MicrosoftLogging.sln
mono: none
dotnet: 2.0.0
dist: trusty
install:
  - dotnet restore
script:
  - dotnet build
deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x ./deploy.sh && ./deploy.sh $TRAVIS_BUILD_NUMBER $MYGET_KEY
  on: 
    branch: master