language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
solution: Discord.Addons.MicrosoftLogging.sln
deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x ./deploy.sh && ./deploy.sh $MYGET_KEY
  on: 
    branch: master